---
# ChIP-seq configuration file
#
# relative paths are okay
#
# provide paths to fastq files of unmatched reads (multiple files for each read are accepted)
unmatched:
    - ../demultiplex-spn1-chipseq-2/fastq/unmatched.fastq.gz

genome:
    annotation_workflow: /n/groups/winston/jc459/intragenic/build-annotations-cerevisiae/

spike_in:
    name: Spom
    fasta: /n/groups/winston/jc459/spt5/genome/S_pombe.ASM294v2.fa
    # transcript_annotation: ../genome/annotations/S_pombe_alltranscripts-adjustedTSS.bed

factor: Spn1 #name of the factor being ChIP'ed

input_samples:
    non-depleted-untagged-input-3:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/non-depleted-untagged-input-3.fastq.gz
        barcode: ATCACG # [STRING] sample barcode
        group: non-depleted  # [STRING] sample group tag. Do not use underscores ("_").
        pass-qc: True  # [True|False] Should this sample be used for peakcalling, and included in "passing" heatmaps, metagenes, scatter plots, etc? Leave True for initial pipeline run, and rerun pipeline with False if a sample fails quality controls.
        spikein: True
    non-depleted-untagged-input-4:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/non-depleted-untagged-input-4.fastq.gz
        barcode: TTAGGC
        group: non-depleted
        pass-qc: True
        spikein: True
    depleted-untagged-input-3:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/depleted-untagged-input-3.fastq.gz
        barcode: CGATGT
        group: depleted
        pass-qc: True
        spikein: True
    depleted-untagged-input-4:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/depleted-untagged-input-4.fastq.gz
        barcode: TGACCA
        group: depleted
        pass-qc: True
        spikein: True

# ChIP sample metadata
chip_samples:
    non-depleted-Spn1-IP-1:  # [STRING] sample name. Do not use underscores ("_").
        fastq: ../demultiplex-spn1-chipseq-2/fastq/non-depleted-Spn1-IP-1.fastq.gz
        barcode: ACAGTG # [STRING] sample barcode
        group: non-depleted  # [STRING] sample group tag. Do not use underscores ("_").
        control: non-depleted-untagged-input-3  # [STRING] name of the corresponding input samples. Must be present in the input_samples listed above.
        pass-qc: True  # [True|False] Should this sample be used for peakcalling, and included in "passing" heatmaps, metagenes, scatter plots, etc? Leave True for initial pipeline run, and rerun pipeline with False if a sample fails quality controls.
        spikein: True  # [True|True] Does the sample have a spikein?
    non-depleted-Spn1-IP-2:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/non-depleted-Spn1-IP-2.fastq.gz
        barcode: CAGATC
        group: non-depleted
        control: non-depleted-untagged-input-4
        pass-qc: True
        spikein: True
    depleted-Spn1-IP-1:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/depleted-Spn1-IP-1.fastq.gz
        barcode: GCCAAT
        group: depleted
        control: depleted-untagged-input-3
        pass-qc: True
        spikein: True
    depleted-Spn1-IP-2:
        fastq: ../demultiplex-spn1-chipseq-2/fastq/depleted-Spn1-IP-2.fastq.gz
        barcode: ACTTGA
        group: depleted
        control: depleted-untagged-input-4
        pass-qc: True
        spikein: True

# comparisons to be made in differential occupancy,  data visualization, scatterplots, etc, etc.
comparisons:
    libsizenorm:
        - depleted: non-depleted
    spikenorm:
        - depleted: non-depleted  # It's okay to have no comparisons if no spikein normalized comparisons are to be made

# [INT] binsizes for scatterplots
scatterplot_binsizes:
    - 200

# cutadapt settings
cutadapt:
    qual_cutoff: 20  # [INT] quality cutoff for cutadapt 3' trimming

# bowtie2 alignment settings
bowtie2:
    index-path: /n/groups/winston/jc459/intragenic/genome/bowtie2_indexes # directory to create index files, if they don't already exist in that directory

    minmapq : 5

peakcalling:
    bw: 250 # bandwidth for model building: set as sonication fragment size
    llocal: 2000  # large region for calculating local lambda
    slocal: 500  # small region for calculating local lambda
    mfold_low: 2  #
    mfold_high: 50
    idr: 0.05  # IDR cutoff

# for smoothed coverage tracks
smooth_bandwidth: 20  # [INT] bandwidth of Gaussian kernel used to smooth coverage

# DESeq2 differential occupancy settings
differential_occupancy:
    fdr: 0.1  # [FLOAT in (0,1)] false discovery rate threshold
    fold-change-threshold: 1  # [FLOAT] fold-change for hypothesis. Absolute fold-change, NOT log2(FC).
    annotations:  # paths to BED format annotation files of regions to test differential occupancy, in addition to called peaks
        verified-coding-genes: ../genome/steinmetz_scer_verified_coding_genes.bed

# data visualization settings
plot_figures: True  # [True|False] plot heatmaps and metagenes?
figures:
    verified-transcripts-nonoverlapping-slopR300-TSS:  # [STRING] name of figure. Do not include underscores ("_")
        annotations:
            nonoverlapping-coding-genes:  # [STRING] name of region. Do not include underscores ("_"). More than one region can be plotted.
                path: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed  # path to BED6 file of regions
                label: nonoverlapping coding genes  # [STRING] label for region
                n_clusters: 1  # [INT] number of clusters to separate region into. Leave 1 for no clustering. Basic k-means clustering is used.
        parameters:
            type: absolute  # [absolute|scaled] Plot absolute distances, or scale all annotations to the same length. For MNase-seq you almost always want absolute distance
            binsize: 20  # [INT] binsize to summarise data
            binstat: mean  # [mean|median|min|max|sum|std] operation used to summarise data
            refpoint: TSS  # [TSS|TES|center] reference point in region. TSS and TES correspond to the 5' and 3' ends, respectively.
            refpointlabel: TSS  # [STRING] label for reference point
            upstream: 400  # [INT] nucleotides upstream of reference point to plot. Must be a multiple of the binsize.
            dnstream: 1500  # [INT] maximum nucleotides downstream of reference point to plot. Must be a multiple of the binsize.
            nan_afterend: True  # [True|False] Should data after the end of the annotation be left out? Useful for length-sorted heatmaps.
            pct_cutoff: .95  # [FLOAT in (0,1)] Percentile of the data to set as the maximum of the colorbar in heatmaps
            log_transform: False
            spread_type: quantile  # [conf_int|quantile] Plot 95% confidence interval of the mean, or quantiles of the data.
            trim_pct: 0.25  # [FLOAT in (0,1)] For confidence intervals, this is the percent to winsorize before taking the mean. For quantiles, this is the lower quantile.
            arrange: length   # [no|length|cluster] No: keep annotations in order of annotation file. Length: sort annotations in order of length before plotting. Cluster: try to plot annotations with similar data close to one another, using optimal leaf ordering of hierarchical clustering
            # cluster_conditions:  # if arrange: cluster, the conditions to be used for clustering
            #     - non-depleted
            #     - depleted
            # cluster_five: -500  # [INT] 5' boundary of the data to be used for clustering, relative to the reference point.
            # cluster_three: 500  # [INT] 3' boundary of the data to be used for clustering, relative to the reference point
            heatmap_colormap: inferno  # [viridis|inferno|magma|plasma] colormap for heatmaps
    verified-transcripts-scaled:
        annotations:
            nonoverlapping-coding-genes:
                path: /n/groups/winston/jc459/intragenic/genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
                label: nonoverlapping coding genes
                n_clusters: 1
        parameters:
            type: scaled # absolute | scaled
            binsize : 20
            binstat : mean # mean | median | min | max | sum | std
            scaled_length: 2000 # int
            upstream : 500 # int
            dnstream : 500 # int
            refpointlabel : TSS # string: label for 5prime reference point
            endlabel : CPS # string: label for 3prime reference point
            pct_cutoff : .95 # winsorize data above this percentile in heatmaps
            log_transform: False
            spread_type: quantile
            trim_pct : 0.25
            arrange: length
            heatmap_colormap : inferno  # viridis | inferno | magma | plasma

# maximum number of threads to use if running locally
threads: 4  # [INT]
